env:
  browser: true
  jquery: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  block-scoped-var:
    - error
  curly:
    - error
  eqeqeq:
    - error
  no-use-before-define:
    - error
  camelcase:
    - error
  no-multi-assign:
    - error
  one-var:
    - error
    - never
  func-style:
    - error
  keyword-spacing:
    - error
  brace-style:
    - error
  comma-spacing:
    - error
  max-len:
    - error
    - 120
  no-tabs:
    - error
  no-console:
    - off
  space-infix-ops:
    - error
